name: YouXiaoQiPrint
options:
  bundleIdPrefix: com.fjxm
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
targets:
  YouXiaoQiPrint:
    type: application
    platform: iOS
    sources:
      - path: YouXiaoQiPrint
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fjxm.print.ios
        INFOPLIST_FILE: YouXiaoQiPrint/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets:
        - YouXiaoQiPrintTests
  YouXiaoQiPrintTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: YouXiaoQiPrintTests
    dependencies:
      - target: YouXiaoQiPrint

